### ISSUE TITLE
Support nodejs 4.0.0

### ISSUE THREAD

**Issue by TheBanHammer** [calzoneman/sync#502]
I am getting an error when attempting to run npm install in the sync directory.

This is the build error:

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /download/sync/node_modules/cytubefilters
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! cytubefilters@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cytubefilters@0.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cytubefilters package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cytubefilters
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /download/sync/npm-debug.log
```

And this is the npm-debug.log is available here: http://pastebin.com/qhEiEjrk (was too long for github)

**Comment by calzoneman** [comment]
As discussed in IRC, this is because I haven't yet updated all of the dependencies to be compatible with nodejs 4.0.0.  Renaming the title of the issue to reflect that.

**Comment by calzoneman** [comment]
It looks like `nan` completely redesigned their API so it's going to be a huge pain to port cytubefilters over.

**Comment by nuclearace** [comment]
Also, socket.io's npm version is broken for 4.0.0. I've been trying to get rauch to update npm.
