### ISSUE TITLE
Error: Cannot find module 'cytube-common/lib/redis/frontendpool'

### ISSUE THREAD

**Issue by AlTech98** [calzoneman/sync#561]
I've installed cytube cloning git and then npm install but it crash when i try to start it
Here is the error:

```

FATAL: Failed to require() lib/server.js
Possible causes:
  * You haven't run `npm run build-server` to regenerate the runtime
  * You've upgraded node/npm and haven't rebuilt dependencies (try `npm rebuild` or `rm -rf node_modules && npm install`)
  * A dependency failed to install correctly (check the output of `npm install` next time)
Error: Cannot find module 'cytube-common/lib/redis/frontendpool'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/altech/CyTube/lib/backend/backendmodule.js:15:41)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/altech/CyTube/lib/server.js:31:29)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

```

**Comment by calzoneman** [comment]
Fixed by https://github.com/calzoneman/sync/commit/98d3090c7d7899bb72b8daa1d1e4355c1720ad6b.  Sorry about that, had a development import end up in the normal code path.
