### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#570]
When try install npm it happens this error:

```
npm http GET https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/compression
npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/cheerio
npm http GET https://registry.npmjs.org/cookie-parser
npm http GET https://registry.npmjs.org/create-error
npm http GET https://registry.npmjs.org/csrf
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express-minify
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/http-errors
npm http GET https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/json-typecheck
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/mysql
npm http GET https://registry.npmjs.org/nodemailer
npm http GET https://registry.npmjs.org/oauth
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/socket.io-redis
npm http GET https://registry.npmjs.org/source-map-support
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/yamljs
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/babel
npm http GET https://registry.npmjs.org/status-message-polyfill
npm http 304 https://registry.npmjs.org/body-parser
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/cookie-parser
npm http 304 https://registry.npmjs.org/cheerio
npm http 304 https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/compression
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/create-error
npm http 304 https://registry.npmjs.org/http-errors
npm http 304 https://registry.npmjs.org/csrf
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/mysql
npm http 304 https://registry.npmjs.org/morgan
npm http 304 https://registry.npmjs.org/express-minify
npm http 304 https://registry.npmjs.org/oauth
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/serve-static
npm http 304 https://registry.npmjs.org/json-typecheck
npm http 304 https://registry.npmjs.org/nodemailer
npm http 200 https://registry.npmjs.org/source-map-support
npm http 304 https://registry.npmjs.org/redis
npm http 304 https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/jade
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm http 304 https://registry.npmjs.org/socket.io-redis
npm http 304 https://registry.npmjs.org/babel
npm http 404 https://registry.npmjs.org/status-message-polyfill
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/public_html/sync/sync
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http 304 https://registry.npmjs.org/yamljs
npm http 304 https://registry.npmjs.org/coffee-script
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/public_html/sync/sync/npm-debug.log
npm ERR! not ok code 0
```

**Comment by calzoneman** [comment]
node v0.10.25 and npm v1.3.10 are extremely old versions.  I advise you install the latest version as detailed in https://nodejs.org/en/download/package-manager/.
