### ISSUE TITLE
Error after Ubuntu update.

### ISSUE THREAD

**Issue by Sirphr** [calzoneman/sync#640]
```
[SEVERE] Unhandled rejection: Error: /home/sync/templates/head.pug:8:50
    6|   meta(name="description", content=siteDescription)
    7|   meta(name="author", content=siteAuthor)
  > 8|   meta(name="google-site-verification", content=2rFVSW0grMKuDXvwBtF48xS9Dm2NWHAXl7w3Go8r1Gg)
--------------------------------------------------------^
    9| 
    10|   title= siteTitle
    11|   link(href="/css/sticky-footer-navbar.css", rel="stylesheet")

Syntax Error: Identifier directly after number
    at makeError (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-error/1.3.1/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-lexer/2.3.0/node_modules/pug-lexer/index.js:58:15)
    at Lexer.assertExpression (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-lexer/2.3.0/node_modules/pug-lexer/index.js:86:12)
    at Lexer.attrs (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-lexer/2.3.0/node_modules/pug-lexer/index.js:1085:18)
    at Lexer.callLexerFunction (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-lexer/2.3.0/node_modules/pug-lexer/index.js:1315:23)
    at Lexer.advance (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-lexer/2.3.0/node_modules/pug-lexer/index.js:1352:15)
    at Lexer.callLexerFunction (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-lexer/2.3.0/node_modules/pug-lexer/index.js:1315:23)
    at Lexer.getTokens (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-lexer/2.3.0/node_modules/pug-lexer/index.js:1371:12)
    at lex (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-lexer/2.3.0/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug/2.0.0-beta6/node_modules/pug/lib/index.js:93:27)
    at Function.loadString [as string] (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-load/2.0.3/node_modules/pug-load/index.js:44:24)
    at /home/sync/node_modules/.resolutions/registry.npmjs.org/pug-load/2.0.3/node_modules/pug-load/index.js:31:27
    at walkAST (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-walk/1.0.0/node_modules/pug-walk/index.js:21:18)
    at /home/sync/node_modules/.resolutions/registry.npmjs.org/pug-walk/1.0.0/node_modules/pug-walk/index.js:98:20
    at Array.reduce (native)
    at walkAndMergeNodes (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-walk/1.0.0/node_modules/pug-walk/index.js:97:18)
    at walkAST (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-walk/1.0.0/node_modules/pug-walk/index.js:35:19)
    at walkAST (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-walk/1.0.0/node_modules/pug-walk/index.js:46:21)
    at /home/sync/node_modules/.resolutions/registry.npmjs.org/pug-walk/1.0.0/node_modules/pug-walk/index.js:98:20
    at Array.reduce (native)
    at walkAndMergeNodes (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-walk/1.0.0/node_modules/pug-walk/index.js:97:18)
    at walkAST (/home/sync/node_modules/.resolutions/registry.npmjs.org/pug-walk/1.0.0/node_modules/pug-walk/index.js:35:19)
```

**Comment by calzoneman** [comment]
The line causing the error is not in core, so I am unable to provide support for this: https://github.com/calzoneman/sync/blob/3.0/templates/head.pug

Please refer to [the PugJS documentation](https://pugjs.org/api/reference.html) for information about the syntax for these files.

**Comment by Xaekai** [comment]
I'll take quoting literals for $1000 Alex.
