### ISSUE TITLE
Cannot create new channel - fresh install

### ISSUE THREAD

**Issue by natrex** [calzoneman/sync#657]
## Server Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [x] Run `npm run build-server` to regenerate `lib/` from `src/`
  - [x] Run `rm -rf node_modules && npm install` to get a fresh install of dependencies
  - [x] Restarted the server
** note ** This is a fresh install.  I've also tried removing all files, dropping the database, and performing the install again from scratch.

### Description of the Problem ###
>> Unable to create a new channel.  I can view videos on a temporary channel, just can't register a permanent one.

  - What triggers the problem? Logging in and attempting to create a new channel.
  - What happens? 
>>Site displays error: "Channel Registration Failed \n Database failure" 
>> Backend logs : 
! DB query failed: INSERT INTO `channels` (`name`, `owner`, `time`, `last_loaded`) VALUES (?, ?, ?, ?)
Substitutions: testroom,username,1490462108246,Sat Mar 25 2017 12:15:08 GMT-0500 (CDT)
{ Error: ER_BAD_FIELD_ERROR: Unknown column 'last_loaded' in 'field list'
>> channels table structure seems to be missing a column?
MariaDB [cytube3]> describe channels;
+-------+-------------+------+-----+---------+----------------+
| Field | Type        | Null | Key | Default | Extra          |
+-------+-------------+------+-----+---------+----------------+
| id    | int(11)     | NO   | PRI | NULL    | auto_increment |
| name  | varchar(30) | NO   | UNI | NULL    |                |
| owner | varchar(20) | NO   | MUL | NULL    |                |
| time  | bigint(20)  | NO   |     | NULL    |                |
+-------+-------------+------+-----+---------+----------------+
  - What do you expect to happen instead?  pls sir, i would like to create a room
  
### System Information ###

  - **Operating System:**  CentOS 7
  - **Node Version:** 6.9.4
  - **CyTube Version:** 3.34.6
  - **Error Messages Displayed:** listed above

### Other notes ###
I tried creating the new columns manually based on the alter statements listed on the commit here [ 
https://github.com/calzoneman/sync/commit/8f266ccd4428d1a76fbeb860c234a5066a0e3f4a ] but to no avail.
Also, I was receiving a bookshelf/knex dependency error and installed knex version 0.11.10 manually 

Any help would be much appreciated.

**Comment by calzoneman** [comment]
Looks like the new columns weren't added to the initialization script.  You can force the update script to create them by forcing the DB version to be an earlier version:

```sql
UPDATE meta SET value = '9' WHERE `key` = 'db_version';
```

**Comment by natrex** [comment]
Looking good, thanks much for your prompt reply.

**Comment by calzoneman** [comment]
Reopening because there is a genuine issue here (the install script isn't creating all the columns) -- the above was just a workaround for you to get your server up and running before it's fixed.

**Comment by ghost** [comment]
I'd like to reopen this as I am also having this problem I believe. The script doesnt seem to have created ANY tables, but I can't be certain as my mysql skills are non-existent. Essentially what happens is that clicking on channels just sends the browser in a loop, where it never stops loading and always waiting for a response. I'm using the latest firefox, the latest version 6 of npm and also the latest version of the script (only installed it this week) on ubuntu 17.x

**Comment by calzoneman** [comment]
Your problem would not be related since in this case the issue was specific to users upgrading an existing database to a newer version, not a fresh install.

I just confirmed that on a clean installation, all the tables are created correctly and I am able to register a channel:

```
MariaDB [cytube_test]> show tables;
Empty set (0.00 sec)

-- After running node index.js and registering a test channel

MariaDB [cytube_test]> show tables;
+-----------------------+
| Tables_in_cytube_test |
+-----------------------+
| aliases               |
| channel_bans          |
| channel_data          |
| channel_libraries     |
| channel_ranks         |
| channels              |
| global_bans           |
| meta                  |
| password_reset        |
| stats                 |
| user_playlists        |
| users                 |
+-----------------------+
12 rows in set (0.00 sec)

MariaDB [cytube_test]> select * from channels;
+----+------+-------+---------------+---------------------+---------------------+
| id | name | owner | time          | last_loaded         | owner_last_seen     |
+----+------+-------+---------------+---------------------+---------------------+
|  1 | test | test  | 1493351992491 | 2017-04-27 20:59:54 | 2017-04-27 20:59:54 |
+----+------+-------+---------------+---------------------+---------------------+
1 row in set (0.00 sec)
```

If it's not working for you, please examine the program output for any errors encountered during initialization or when processing your request.

**Comment by ghost** [comment]
I get the following output when i follow the above:

```
+-------------------+
| Tables_in_cytube3 |
+-------------------+
| users             |
+-------------------+
1 row in set (0.00 sec)
```

I guess that's normal.

After I build, and then run rm -rf node modules && npm install I get the follwing errors

```
Do you want to build now? [y/N]? y

Running babel -D --source-maps --loose es6.destructuring,es6.forOf --out-dir lib/ src/
Error: EACCES: permission denied, open 'lib/account.js.map'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at fs.writeFileSync (fs.js:1347:33)
    at outputFileSync (/home/jinsan/sync/node_modules/output-file-sync/index.js:45:3)
    at write (/home/jinsan/sync/node_modules/babel-cli/lib/babel/dir.js:30:7)
    at handleFile (/home/jinsan/sync/node_modules/babel-cli/lib/babel/dir.js:43:7)
    at /home/jinsan/sync/node_modules/babel-cli/lib/babel/dir.js:61:9
    at Array.forEach (native)
    at handle (/home/jinsan/sync/node_modules/babel-cli/lib/babel/dir.js:59:29)
    at Array.forEach (native)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN bookshelf@0.9.5 requires a peer of knex@>=0.6.10 <0.12.0 but none was installed.
npm ERR! Linux 4.4.0-75-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! CyTube@3.35.1 postinstall: `./postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the CyTube@3.35.1 postinstall script './postinstall.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the CyTube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./postinstall.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs CyTube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls CyTube
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jinsan/sync/npm-debug.log
```



So I force run the postinstall.sh, and it saysa

...
Running
...

then i run screen ./run.sh and get a bunch more errors, I just noticed the address is in use error for port 1337 socket.io

...
[WARN] config: Missing config key config.google-drive; using default: {"html5-ha                                                                                                                                                                                                                                             ck-enabled":false}
[WARN] config: No YouTube v3 API key set.  YouTube links will not work.  See you                                                                                                                                                                                                                                             tube-v3-key in config.template.yaml and https://developers.google.com/youtube/re                                                                                                                                                                                                                                             gistering_an_application for information on registering an API key.
[WARN] config: No Twitch Client ID set.  Twitch VOD links will not work.  See tw                                                                                                                                                                                                                                             itch-client-id in config.template.yaml and https://github.com/justintv/Twitch-AP                                                                                                                                                                                                                                             I/blob/master/authentication.md#developer-setupfor more information on registeri                                                                                                                                                                                                                                             ng a client ID
[INFO] config: Loaded configuration from config.yaml
[INFO] server: Starting CyTube v3.35.1
[SEVERE] Uncaught Exception: Error: listen EADDRINUSE 45.xxx:8443
Error: listen EADDRINUSE 45.76.143.195:8443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
[SEVERE] Uncaught Exception: Error: listen EADDRINUSE 45.xxx:1337
Error: listen EADDRINUSE 45.76.143.195:1337
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
[ERROR] database: ! DB query failed: SELECT * FROM global_bans WHERE 1
[SEVERE] Uncaught Exception: TypeError: _fmt.substring is not a function
TypeError: _fmt.substring is not a function
    at Function.sprintf.parse (/home/jinsan/sync/node_modules/sprintf-js/src/spr                                                                                                                                                                                                                                             intf.js:166:25)
    at sprintf (/home/jinsan/sync/node_modules/sprintf-js/src/sprintf.js:19:34)
    at LegacyLogger.log (/home/jinsan/sync/src/logger.js:74:20)
    at LegacyLogger.error (/home/jinsan/sync/node_modules/@calzoneman/jsli/src/l                                                                                                                                                                                                                                             ogger.js:75:13)
    at Query.cback [as _callback] (/home/jinsan/sync/src/database.js:82:28)
    at Query.Sequence.end (/home/jinsan/sync/node_modules/mysql/lib/protocol/seq                                                                                                                                                                                                                                             uences/Sequence.js:86:24)
    at Query.ErrorPacket (/home/jinsan/sync/node_modules/mysql/lib/protocol/sequ                                                                                                                                                                                                                                             ences/Query.js:88:8)
    at Protocol._parsePacket (/home/jinsan/sync/node_modules/mysql/lib/protocol/                                                                                                                                                                                                                                             Protocol.js:280:23)
    at Parser.write (/home/jinsan/sync/node_modules/mysql/lib/protocol/Parser.js                                                                                                                                                                                                                                             :75:12)
    at Protocol.write (/home/jinsan/sync/node_modules/mysql/lib/protocol/Protoco                                                                                                                                                                                                                                             l.js:39:16)
    at Socket.<anonymous> (/home/jinsan/sync/node_modules/mysql/lib/Connection.j                                                                                                                                                                                                                                             s:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[ERROR] database: ! DB query failed: CREATE TABLE IF NOT EXISTS `channels` (`id`                                                                                                                                                                                                                                              INT NOT NULL AUTO_INCREMENT,`name` VARCHAR(30) NOT NULL,`owner` VARCHAR(20) NOT                                                                                                                                                                                                                                              NULL,`time` BIGINT NOT NULL,`last_loaded` TIMESTAMP NOT NULL DEFAULT 0,`owner_l                                                                                                                                                                                                                                             ast_seen` TIMESTAMP NOT NULL DEFAULT 0,PRIMARY KEY (`id`),UNIQUE(`name`),INDEX(`                                                                                                                                                                                                                                             owner`),INDEX(`last_loaded`),INDEX(`owner_last_seen`)) CHARACTER SET utf8
[SEVERE] Uncaught Exception: TypeError: _fmt.substring is not a function
TypeError: _fmt.substring is not a function
    at Function.sprintf.parse (/home/jinsan/sync/node_modules/sprintf-js/src/spr                                                                                                                                                                                                                                             intf.js:166:25)
    at sprintf (/home/jinsan/sync/node_modules/sprintf-js/src/sprintf.js:19:34)
    at LegacyLogger.log (/home/jinsan/sync/src/logger.js:74:20)
    at LegacyLogger.error (/home/jinsan/sync/node_modules/@calzoneman/jsli/src/l                                                                                                                                                                                                                                             ogger.js:75:13)
    at Query.cback [as _callback] (/home/jinsan/sync/src/database.js:82:28)
    at Query.Sequence.end (/home/jinsan/sync/node_modules/mysql/lib/protocol/seq                                                                                                                                                                                                                                             uences/Sequence.js:86:24)
    at Query.ErrorPacket (/home/jinsan/sync/node_modules/mysql/lib/protocol/sequ                                                                                                                                                                                                                                             ences/Query.js:88:8)
    at Protocol._parsePacket (/home/jinsan/sync/node_modules/mysql/lib/protocol/                                                                                                                                                                                                                                             Protocol.js:280:23)
    at Parser.write (/home/jinsan/sync/node_modules/mysql/lib/protocol/Parser.js                                                                                                                                                                                                                                             :75:12)
    at Protocol.write (/home/jinsan/sync/node_modules/mysql/lib/protocol/Protoco                                                                                                                                                                                                                                             l.js:39:16)
    at Socket.<anonymous> (/home/jinsan/sync/node_modules/mysql/lib/Connection.j                                                                                                                                                                                                                                             s:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
[INFO] tor: Loaded Tor IP list
[ERROR] tor: TypeError: Cannot read property 'stack' of null
    at /home/jinsan/sync/src/tor.js:55:72
    at /home/jinsan/sync/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
...

I'm not sure why :( It looked similar to the other issue in this thread, hence I thought it was a db issue

**Comment by calzoneman** [comment]
The `Uncaught Exception: TypeError: _fmt.substring is not a function` is something I just fixed in the latest commit, so if you want to pull and re-run `npm run build-server` then it will print the correct error message.

My guess would be that you're using a version of MySQL that defaults to `TRADITIONAL` mode and therefore doesn't accept `DEFAULT 0` for timestamp columns, but I would have to see the actual error message to confirm.

**Comment by ghost** [comment]
ok so after pulling the new version, I now get db errors instead of thge other stuff.

```
[ERROR] google2vtt: Error: ENOENT: no such file or directory, scandir '/home/jinsan/sync/google-drive-subtitles'
    at Error (native)
[ERROR] database: ! DB query failed: SELECT * FROM global_bans WHERE 1
[ERROR] database: Error: ER_NO_SUCH_TABLE: Table 'cytube3.global_bans' doesn't exist
[ERROR] database: ! DB query failed: CREATE TABLE IF NOT EXISTS `channels` (`id` INT NOT NULL AUTO_INCREMENT,`name` VARCHAR(30) NOT NULL,`owner` VARCHAR(20) NOT NULL,`time` BIGINT NOT NULL,`last_loaded` TIMESTAMP NOT NULL DEFAULT 0,`owner_last_seen` TIMESTAMP NOT NULL DEFAULT 0,PRIMARY KEY (`id`),UNIQUE(`name`),INDEX(`owner`),INDEX(`last_loaded`),INDEX(`owner_last_seen`)) CHARACTER SET utf8
[ERROR] database: Error: ER_INVALID_DEFAULT: Invalid default value for 'last_loaded'
Database failure
[ERROR] database: ! DB query failed: CREATE TABLE IF NOT EXISTS `channel_data` (`channel_id` INT NOT NULL,`key` VARCHAR(20) NOT NULL,`value` MEDIUMTEXT CHARACTER SET utf8mb4 NOT NULL,PRIMARY KEY (`channel_id`, `key`),FOREIGN KEY (`channel_id`) REFERENCES `channels`(`id`) ON DELETE CASCADE) CHARACTER SET utf8
[ERROR] database: Error: ER_CANNOT_ADD_FOREIGN: Cannot add foreign key constraint
Database failure
[INFO] tor: Loaded Tor IP list
[ERROR] tor: Failed to write to /home/jinsan/sync/torlist: null

```

Would you like me to open a new ticket, and what should I name it as I dont know what the error refers to other than the db.

**Comment by calzoneman** [comment]
I think this will fix it so you won't need to create a new ticket:

```sql
SET sql_mode = 'Ansi';
```

**Comment by calzoneman** [comment]
For more information: https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html

>The following examples use DEFAULT 0, a default that can produce warnings or errors depending on whether strict SQL mode or the NO_ZERO_DATE SQL mode is enabled. Be aware that the TRADITIONAL SQL mode includes strict mode and NO_ZERO_DATE. See Section 6.1.8, “Server SQL Modes”.

Someone else who ran into this issue reported that setting the SQL mode to ANSI solved the problem for them.  MariaDB also allows this by default, but I don't remember if Ubuntu packages it (MariaDB is a fork of MySQL, on which I do all my development and testing; I don't actually own a machine with plain MySQL on it anymore, so some incompatibilities like this one may slip through the cracks).

**Comment by ghost** [comment]
mm so should i drop the table and recreate teh table and user as per the guide, or will that alone fix it? As I ran it, it said fine. Then i ran the run.sh and it's giving me the same db errors. I guess I may have to consider changing the os.

**Comment by calzoneman** [comment]
The table was never created as per your error and `SHOW TABLES` output above.  If you mean recreating the database, no that will not be necessary.

I didn't ask exactly where the other person who ran into this changed it.  You should be able to search the internet for help with changing the SQL mode.

I don't think switching the OS will be necessary.

**Comment by ghost** [comment]
ok I'll try to google, meanwhile can is there anotgher way of creating the tables, without doing it by hand, or will it require adding tables one by one. I guess that won't guarantee it can be written to though would it?

**Comment by ghost** [comment]
when checking for the mode it's in i get the following
`mysql> SELECT @@GLOBAL.sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@GLOBAL.sql_mode                                                                                                                         |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
`

I'll try changing it and report back

**Comment by ghost** [comment]
bad news: i couldn't get it to work for some reason, kept spitting out db error.
Good news, I started from scratch, with a fresh install and it works as it should now, I believe.

Thanks for the assist

**Comment by calzoneman** [comment]
I installed MySQL in a VM to investigate the steps for fixing it, in case someone else encounters the same issue.  It's now documented on [the installation guide](https://github.com/calzoneman/sync/wiki/CyTube-3.0-Installation-Guide#note-for-mysql-users).
